name: Sync Reduced Waste Library to Alabee Vault

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          
      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: '.'
          # Notice the specific folder at the end of the destination
          destination: 'alabee-github-vault-dylanyoung3244/Reduced-Waste-Library'
          parent: false
